[".config/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/nvim/snippets"]
    type = "archive"
    url = "https://github.com/honza/vim-snippets/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/snippets/**"]
