".oh-my-zsh":
  type: archive
  url: "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  stripComponents: 1
  # waiting for https://github.com/twpayne/chezmoi/issues/1614#issuecomment-966524408
  # exact: true
  refreshPeriod: "168h"
".oh-my-zsh/custom/themes/powerlevel10k":
  type: "archive"
  url: "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
