repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: dot_config/nvim/_lazy-lock.json
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
  # - repo: https://github.com/JohnnyMorganz/StyLua
  #   rev: v0.18.0
  #   hooks:
  #     - id: stylua-github
  #       args: [--config-path=./dot_config/nvim/stylua.toml]
